---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
    
ratings:
  paths:
  - "**.rb"

exclude_paths: 
