inherit_from: .rubocop_todo.yml

Documentation:
  Exclude:
    - "lib/cequel/version.rb"
    - "lib/cequel/errors.rb"
    - "lib/cequel/record/errors.rb"

HashSyntax:
  Exclude:
    - "lib/cequel/record/tasks.rb"

IfUnlessModifier:
  Enabled: false

DoubleNegation:
  Enabled: false
