name: CI

on:
  push:
    branches:
      # - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          # - '3.0'
          # - '3.1'
        rails:
          - '5.2'
          # - '6.0'
          # - '6.1'
          # - '7.0'
        cassandra:
          - '2.2'
          - '3.0'
          - '3.11'
          # - '4.0'
        exclude:
          - ruby: '2.6'
            rails: '7.0'
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }} / Cassandra ${{ matrix.cassandra }}
    services:
      cassandra:
        image: cassandra:${{ matrix.cassandra }}
        ports:
          - 9042:9042
        options: >-
          --health-cmd "cqlsh -e 'SHOW VERSION' localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
       BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake test
        env:
          RAILS_ENV: test
